language: rust
rust: stable

os: linux
cache: cargo

before_install:
  - sudo apt-get install libv4l-dev

jobs:
  allow_failures:
    env:
      - CAN_FAIL=true
  fast_finish: true
  include:
    - name: check
      script:
        - cargo check
    - name: test
      script:
        - cargo test
    - name: fmt
      before_script:
        - rustup component add rustfmt
      script:
        - cargo fmt -- --check
    - name: clippy
      env: CAN_FAIL=true
      before_script:
        - rustup component add clippy
      script:
        - cargo clippy -- -D warnings
